apps/project/urls.py
from django.urls import include, path
from rest_framework import routers

from apps.project.views import (
    UpdateDataView, ProjectCreateView, ProjectUpdateView,
    VersionListView, VersionCreateView, VersionCopyView,
    VersionUpdateView, RegisterListView, RegisterCreateView, RegisterUpdateView,
    RegisterViewSet, FieldViewSet, FieldChoiceViewSet, FileUploadView, FileDownloadView, FieldListView, VersionViewSet
)

router = routers.DefaultRouter()
router.register(r'registers', RegisterViewSet)
router.register(r'versions', VersionViewSet)
router.register(r'fields-list', FieldViewSet)
router.register(r'field-choices', FieldChoiceViewSet)

app_name = 'project'

urlpatterns = [
    path('', include(router.urls)),

    # Project
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProjectUpdateView.as_view(), name='update'),

    # Version
    path('<int:pk>/versions/', VersionListView.as_view(), name='version-list'),
    path('version-create/', VersionCreateView.as_view(), name='version-create'),
    path('version-update/<int:pk>/', VersionUpdateView.as_view(), name='version-update'),
    path('version-copy/', VersionCopyView.as_view(), name='version-copy'),

    # Register
    path('<int:pk>/registers/', RegisterListView.as_view(), name='register-list'),
    path('register-create/', RegisterCreateView.as_view(), name='register-create'),
    path('register-update/<int:pk>/', RegisterUpdateView.as_view(), name='register-update'),
    path('fileUpload/', FileUploadView.as_view(), name='file-upload'),
    path('<int:pk>/registers/fileDownload/', FileDownloadView.as_view(), name='file-download'),
    path('fields/',FieldListView.as_view(), name='field-list'),
    path('updateData/', UpdateDataView.as_view(), name='update-data'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('_nested_admin/', include('nested_admin.urls')),
    path('', include('apps.common.urls')),
    path('project/', include('apps.project.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/project/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Div, Submit
from django.urls import reverse_lazy

from apps.common.forms import CustomBaseModelForm
from apps.project.models import Project, Version, Register
from apps.project.validators import validate_hex_value


class ProjectForm(CustomBaseModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        submit_text = 'Update changes' if self.instance.id else 'Save changes'
        self.helper = FormHelper()

        # Change form action w.r.to create or update request.
        # Form action is required as we are using form in a pop-up
        if self.instance.id:
            self.helper.form_action = reverse_lazy(
                'project:update',
                kwargs={'pk': self.instance.id}
            )
        else:
            self.helper.form_action = reverse_lazy('project:create')

        self.helper.layout = Layout(
            'name',
            'description',
            Row(
                Column('address_size', css_class='form-group col-md-6 mb-0'),
                Column('word_size', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Div(
                Submit('submit', submit_text),
                css_class='mt-3 text-right'
            ),
        )

    class Meta:
        model = Project
        fields = (
            'name', 'description',
            'address_size', 'word_size'
        )


class VersionForm(CustomBaseModelForm):

    def __init__(self, *args, **kwargs):
        project_field_disabled = kwargs.pop('project_field_disabled', False)
        super().__init__(*args, **kwargs)

        submit_text = 'Update changes' if self.instance.id else 'Save changes'
        self.helper = FormHelper()

        # Change form action w.r.to create or update request.
        # Form action is required as we are using form in a pop-up
        if self.instance.id:
            self.helper.form_action = reverse_lazy(
                'project:version-update',
                kwargs={'pk': self.instance.id}
            )
        else:
            self.helper.form_action = reverse_lazy('project:version-create')

        # Make project field readonly is project_field_disabled is passed
        if project_field_disabled:
            self.fields['project'].widget.attrs['readonly'] = True

        self.helper.layout = Layout(
            'project',
            'name',
            Div(
                Submit('submit', submit_text),
                css_class='mt-3 text-right'
            ),
        )

    class Meta:
        model = Version
        fields = ('project', 'name')


class RegisterForm(CustomBaseModelForm):
    address = forms.CharField(
        validators=[validate_hex_value],
        max_length=20
    )

    def __init__(self, *args, **kwargs):
        version_field_disabled = kwargs.pop('version_field_disabled', False)
        super().__init__(*args, **kwargs)

        submit_text = 'Update changes' if self.instance.id else 'Save changes'
        self.helper = FormHelper()

        # Change form action w.r.to create or update request.
        # Form action is required as we are using form in a pop-up
        if self.instance.id:
            self.helper.form_action = reverse_lazy(
                'project:register-update',
                kwargs={'pk': self.instance.id}
            )
        else:
            self.helper.form_action = reverse_lazy('project:register-create')

        # Make project field readonly is project_field_disabled is passed
        if version_field_disabled:
            self.fields['version'].widget.attrs['readonly'] = True

        self.helper.layout = Layout(
            'version',
            'name',
            Row(
                Column('address', css_class='form-group col-md-6 mb-0'),
                Column('size', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            'description',
            Div(
                Submit('submit', submit_text),
                css_class='mt-3 text-right'
            ),
        )

    class Meta:
        model = Register
        fields = ('version', 'name', 'address', 'size', 'description')

apps/project/views.py
from ensurepip import version
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.http import url_has_allowed_host_and_scheme
from django.views.generic import ListView, CreateView, UpdateView
from django.views import View
from rest_framework import viewsets
from django.http import FileResponse, JsonResponse
from django.db.models import Prefetch
import re
from apps.common.mixins import RequestInjectMixin
from apps.project.forms import ProjectForm, VersionForm, RegisterForm
from apps.project.models import Project, Version, Register, Field, FieldChoice
from apps.project.serializers import RegisterSerializer, FieldSerializer, FieldChoiceSerializer, VersionSerializer
import xlsxwriter
import openpyxl
from rest_framework.response import Response

class CommonMessageMixin(SuccessMessageMixin):
    """
    Since all of the forms are pop-up, showing message on field is difficult
    So message are shown as error messages
    """

    def form_invalid(self, form):
        # Extract Error from forms
        for k, v in form.errors.items():
            messages.error(self.request, v)
        return redirect(self.request.META["HTTP_REFERER"])


class CommonVersionCreateUpdateMixin(
    CommonMessageMixin,
    RequestInjectMixin,
    LoginRequiredMixin,
):
    """
    Copy common logic of create and update implementation if Version Crud
    """

    queryset = Version.objects.all()
    form_class = VersionForm
    success_url = reverse_lazy("project:version-list")
    template_name = "project/snippet/form-create-update.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        # Disabled project field while creating project from version list page
        kwargs["project_field_disabled"] = bool(
            self.request.GET.get("project_field_disabled")
        )
        return kwargs

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""

        # If next_url is passed from frontend redirect to that url after success
        next_url = self.request.GET.get("next")
        if next_url and url_has_allowed_host_and_scheme(next_url, settings.ALLOWED_HOSTS):
            return redirect(next_url)

        return reverse_lazy(
            "project:version-list", kwargs={"pk": self.object.project.id}
        )

    def get_initial(self):
        initial = super().get_initial()
        # If project_id is passed as query parameters set that initial value
        project_id = self.request.GET.get("project")
        if project_id:
            initial["project"] = get_object_or_404(Project, id=project_id)
        return initial


class CommonRegisterCreateUpdateMixin(
    CommonMessageMixin,
    RequestInjectMixin,
    LoginRequiredMixin,
):
    """
    Copy common logic of create and update implementation if Register Crud
    """

    queryset = Register.objects.all()
    form_class = RegisterForm
    success_url = reverse_lazy("project:register-list")
    template_name = "project/snippet/form-create-update.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        # Disabled project field while creating project from version list page
        kwargs["version_field_disabled"] = bool(
            self.request.GET.get("version_field_disabled")
        )
        return kwargs

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        return reverse_lazy(
            "project:register-list", kwargs={"pk": self.object.version.id}
        )


class ProjectCreateView(
    RequestInjectMixin, CommonMessageMixin, LoginRequiredMixin, CreateView
):
    queryset = Register.objects.all()
    serializer_class = RegisterSerializer

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    success_message = "Successfully Created New Project"


class ProjectUpdateView(
    RequestInjectMixin, CommonMessageMixin, LoginRequiredMixin, UpdateView
):

    queryset = Project.objects.all()
    form_class = ProjectForm
    success_url = reverse_lazy("common:home")
    template_name = "project/snippet/form-create-update.html"
    success_message = "Successfully Updated Project"


class VersionListView(LoginRequiredMixin, ListView):

    queryset = Version.objects.all()
    template_name = "project/version-list.html"
    context_object_name = "versions"
    paginate_by = 5

    def get_queryset(self):
        """
        Filter versions using project id provided in URL
        """
        return super().get_queryset().filter(project_id=self.kwargs.get("pk"))

    def get_context_data(self, *args, **kwargs):
        version_id = self.request.GET.get("register_id")
        status = self.request.GET.get("status")
        type = self.request.GET.get("type")

        if status == "V":
            if type == "delete":
                version = Version.objects.get(id=version_id)
                version.delete()
                return
        else:
            data = super().get_context_data(*args, **kwargs)
            data["project"] = get_object_or_404(
                Project, id=self.kwargs.get("pk"))
            return data


class VersionCreateView(CommonVersionCreateUpdateMixin, CreateView):

    success_message = "Successfully Created New Version"


class VersionUpdateView(CommonVersionCreateUpdateMixin, UpdateView):

    success_message = "Successfully Updated Version"


class VersionCopyView(View):
    def get(self, request, *args, **kwargs):
        version_id = self.request.GET.get("version")
        if version_id:
            old_version = Version.objects.get(id=version_id)
            old_register = Register.objects.filter(version_id=old_version.id)
            new_version = Version.objects.create(
                project_id=old_version.project_id, name="Copy "+old_version.name)
            for r in old_register:
                new_register = Register.objects.create(version_id=new_version.id, name=r.name, address=r.address,
                                                       size=r.size, description=r.description)
                old_field = Field.objects.filter(register_id=r.id)
                for f in old_field:
                    new_field = Field.objects.create(register_id=new_register.id, range_upper=f.range_upper, range_lower=f.range_lower,
                                                     type=f.type, unit_scale=f.unit_scale, unit_type=f.unit_type, name=f.name, description=f.description,
                                                     value_min=f.value_min, value_max=f.value_max)
                    old_choice = FieldChoice.objects.filter(field_id=f.id)
                    for c in old_choice:
                        FieldChoice.objects.create(
                            field_id=new_field.id, name=c.name, desc=c.desc, value=c.value)
            return redirect("project:version-list", old_version.project_id)


class FieldListView(LoginRequiredMixin, ListView):
    queryset = Field.objects.all()
    template_name = "project/field-list.html"
    context_object_name = "fields"
    paginate_by: int = 500

    def get_queryset(self):
        return list(super().get_queryset())

    def get_context_data(self, *args, **kwargs):
        register_id = self.request.GET.get("register_id")
        field_id = self.request.GET.get("field_id")
        choice_id = self.request.GET.get("choice_id")
        status = self.request.GET.get("status")
        type = self.request.GET.get("type")
        value = self.request.GET.get("value")

        if status == "F":
            if type == "delete":
                f = Field.objects.get(id=register_id)
                f.delete()
                return
            else:
                f = Register.objects.get(
                    id=register_id).fields.get(id=field_id)
                setattr(f, type, value)
                f.save()
        elif status == "C":
            if type == "delete":
                choice = FieldChoice.objects.get(id=register_id)
                choice.delete()
            else:
                choice = (
                    Register.objects.get(id=register_id)
                    .fields.get(id=field_id)
                    .choices.get(id=choice_id)
                )
                setattr(choice, type, value)
                choice.save()
        else:
            data = super().get_context_data(*args, **kwargs)
            return data


class RegisterListView(LoginRequiredMixin, ListView):
    queryset = Register.objects.all()
    template_name = "project/register-list.html"
    context_object_name = "registers"
    paginate_by = 500

    def get_queryset(self):
        """
        Filter versions using version id provided in URL
        """
        registers = (
            super()
            .get_queryset()
            .filter(version_id=self.kwargs.get("pk"))
            .prefetch_related('fields')
            .order_by("address")
        )
        return list(registers)

    def get_context_data(self, *args, **kwargs):

        register_id = self.request.GET.get("register_id")
        field_id = self.request.GET.get("field_id")
        choice_id = self.request.GET.get("choice_id")
        status = self.request.GET.get("status")
        type = self.request.GET.get("type")
        value = self.request.GET.get("value")
        if status == "R":
            r = Register.objects.get(id=register_id)
            if type == "address":
                value = int(value, 16)
            if type == "delete":
                r.delete()
                return
            setattr(r, type, value)
            r.save()

        elif status == "F":
            if type == "delete":

apps/project/templates/project/field-list.html
{% extends 'base.html' %}
{% load custom_tags %}

<div class="container">
  {{ fields }}
  {% block body %}
  {% include 'project/snippet/version-breadcrumb.html' with project=project version=version %}

  {% if request.user.is_authenticated %}
  <div class="my-4 container text-right">
    <button data-url="{% url 'project:register-create' %}?version_field_disabled=true&version={{ version.id }}"
      data-target="create-update-modal" data-title="Create New Version"
      class="btn btn-success text-right text-white modal-popup">
      Create New Field
    </button>
  </div>
  {% endif %}

  <div class="container main-div">
    <div class="table-responsive-sm">
      <table class="table table-striped table-bordered table-hover table-condensed text-xs-left">
        <thead>
          <tr class="table-primary text-center">
            <th scope="col">ID</th>
            <th scope="col">Range Lower</th>
            <th scope="col">Range Upper</th>
            <th scope="col">Type</th>
            <th scope="col">Scale</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Value Min</th>
            <th scope="col">Value Max</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody class="text-center">
          {% for field in fields %}
          <tr>
            <td>{{ field.id}}</td>
            <td><input type="text" class="input-default" id="F-lower" name="F-range_lower-{{ field.register.id }}-{{ field.id}}" value="{{ field.range_lower }}"/></td>
            <td><input type="text" class="input-default" id="F-upper" name="F-range_upper-{{ field.register.id }}-{{ field.id}}" value="{{ field.range_upper }}"/></td>
            <td>
              <select id="F-type" name="F-type-{{ field.register.id }}-{{ field.id}}">
                  <optgroup label="Number">
                    <option value="UINT" {% if field.type == 'UINT' %} selected {% endif %}>UINT</option>
                    <option value="INT" {% if field.type == 'INT' %} selected {% endif %}>INT</option>
                    <option value="BCD" {% if field.type == 'BCD' %} selected {% endif %}>BCD</option>
                    <option value="DOUBLE" {% if field.type == 'DOUBLE' %} selected {% endif %}>DOUBLE64</option>
                    <option value="FLOAT" {% if field.type == 'FLOAT' %} selected {% endif %}>FLOAT32</option>
                  </optgroup>
                  <optgroup label="TEXT"> 
                    <option value="ASCII" {% if field.type == 'ASCII' %} selected {% endif %}>ASCII</option>
                    <option value="UTF8" {% if field.type == 'UTF8' %} selected {% endif %}>UTF8</option>
                  </optgroup>
                  <optgroup label="Selection">
                    <option value="MUX" {% if field.type == 'MUX' %} selected {% endif %}>MUX</option>
                    <option value="FLAG_AH" {% if field.type == 'FLAG_AH' %} selected {% endif %}>FLAG_AH</option>
                    <option value="FLAG_AL" {% if field.type == 'FLAG_AL' %} selected {% endif %}>FLAG_AL</option>
                  </optgroup>
                </select>
              </td>

            <td><input type="text" class="input-default" id="F-unit_scale" name="F-unit_scale-{{ field.register.id }}-{{ field.id}}" value="{{ field.unit_scale }}"/> </td>
            <td><input type="text" class="input-default" id="F-name" name="F-name-{{ field.register.id }}-{{ field.id}}" value="{{ field.name }}"/> </td>
            <td><textarea type="text" class="input-description w-100 p-2 mb-2" id="R-description" cols="30" rows="3" id="F-description" name="F-description-{{ field.register.id }}-{{ field.id}}">{{ field.description }}</textarea></td>
            <td><input type="text" class="input-default" id="F-value_min" name="F-value_min-{{ field.register.id }}-{{ field.id}}" value="{{ field.value_min }}"/></td>
            <td><input type="text" class="input-default" id="F-value_max" name="F-value_max-{{ field.register.id }}-{{ field.id}}" value="{{ field.value_max }}"/></td>
            <td>
              <button class="btn btn-sm btn-danger font-weight-bold" title="Delete Current Choice" id="R-delete"
                name="C-delete-{{choice.id}}">&#10005;
              </button>
            </td>
  

            {% for choice in field.choices.all %}
          <tr class="choice">
            <td></td>
            <td></td>
            <td></td>
            <td> <input type="text" class="input-range" id="C-value"
                name="C-value-{{ field.register.id }}-{{ field.id}}-{{choice.id}}" value="{{ choice.value }}" /> </td>
            <td></td>
            <td></td>
            <td> <input type="text" class="input-default w-75" id="C-name"
                name="C-name-{{ field.register.id }}-{{ field.id}}-{{choice.id}}" value="{{ choice.name }}" /> </td>
            <td> <input type="text" class="input-description-desc" id="C-description"
                name="C-desc-{{ field.register.id }}-{{ field.id}}-{{choice.id}}" value="{{ choice.desc }}" /> </td>
            <td>
              <button class="btn btn-sm btn-danger font-weight-bold" title="Delete Current Choice" id="R-delete"
                name="C-delete-{{choice.id}}">&#10005;
              </button>
            </td>
          </tr>
          {% endfor %}
          {% if field.type == 'MUX' %}
          <tr class="reserved">
            <td></td>
            <td></td>
            <td></td>
            <td> <input type="text" class="input-range" id="C-value"
                name="N-value-{{ register.id }}-{{ field.id}}-{{choice.id}}" value="{{ choice.value}}" /> </td>
            <td>reserved</td>
            <td></td>
            <td> <input type="text" class="input-default w-75" id="C-name"
                name="N-name-{{ register.id }}-{{ field.id}}-{{choice.id}}" value="{{ choice.name }}" /> </td>
            <td> <input type="text" class="input-description-desc" id="C-description"
                name="N-desc-{{ register.id }}-{{ field.id}}-{{choice.id}}" value="{{ choice.desc }}" /> </td>
            <td></td>
          </tr>
          {% endif %}
          </tr>
          {% endfor%}
        </tbody>
      </table>
    </div>

    <div class="mt-5">
      {% include 'snippets/pagination.html' %}
    </div>
  </div>
  {% endblock %}
</div>

apps/project/templates/project/project-list.html
{% if request.user.is_authenticated %}
  <div class="my-4 container text-right">
    <button
      data-url="{% url 'project:create' %}"
      data-target="create-update-modal"
      data-title="Create New Project"
      class="btn btn-success text-right text-white modal-popup"
    >
      Create New Project
    </button>
  </div>
{% endif %}

<div class="container main-div">
  <div class="table-responsive-sm">
    <table class="table table-striped">
      <thead>
      <tr class="table-primary text-center">
        <th scope="col">Project</th>
        <th scope="col">Last Modified</th>
        <th scope="col">Created</th>
        <th scope="col" width="15%">Description</th>
        <th scope="col">Address Size</th>
        <th scope="col">Word Size</th>
        {% if request.user.is_authenticated %}
          <th scope="col">Action</th>
        {% endif %}
      </tr>
      </thead>
      <tbody class="text-center">
      {% for project in projects %}
        <tr>
          <td>
            <a href="{% url 'project:version-list' project.id %}" class="text-decoration-none">
              {{ project.name }}
            </a>
          </td>
          <td>
            {% if project.updated_at %}
              {{ project.updated_at | date:"j/n/Y" }}
            {% else %}
              N/A
            {% endif %}
          </td>
          <td>{{ project.created_by }}</td>
          <td data-toggle="tooltip" data-placement="top" title="{{ project.description }}">
            {{ project.description |truncatechars_html:15 }}
          </td>
          <td>{{ project.address_size }}</td>
          <td>{{ project.word_size }}</td>
          {% if request.user.is_authenticated %}
            <td>
              <button
                  class="btn btn-sm btn-success font-weight-bold modal-popup"
                  data-toggle="tooltip"
                  data-placement="top"
                  title="Add New Version"
                  data-target="create-update-modal"
                  data-url="{% url 'project:version-create' %}?project={{ project.id }}"
              >➕
              </button>
              <button
                class="btn btn-sm btn-info font-weight-bold modal-popup"
                data-toggle="tooltip"
                data-placement="top"
                title="Edit Current Project"
                data-url="{% url 'project:update' project.id %}"
                data-target="create-update-modal"
                data-title="Update {{ project.name }}"
              >🖋
              </button>
              <button
                class="btn btn-sm btn-danger font-weight-bold"
                data-toggle="tooltip"
                data-placement="top"
                title="Delete Current Project"
              >&#10005;
              </button>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="mt-5">
    {% include 'snippets/pagination.html' %}
  </div>
</div>

apps/project/templates/project/version-list.html
{% extends 'base.html' %}

<div class="container">
  {% block body %}
    {% include 'project/snippet/version-breadcrumb.html' with project=project %}

    {% if request.user.is_authenticated %}
      <div class="my-4 container text-right">
        <button
          data-url="{% url 'project:version-create' %}?project_field_disabled=true&project={{ project.id }}"
          data-target="create-update-modal"
          data-title="Create New Version"
          class="btn btn-success text-right text-white modal-popup"
        >
          Create New Version
        </button>
      </div>
    {% endif %}

    <div class="container my-4 main-div">
      <div class="card">
        <div class="card-header">
          Project Information
        </div>
        <div class="card-body">
          <div class="row">
            <span class="font-weight-bold col-md-2">Project:</span>
            <span class="col-md-10">{{ project.name }}</span>
          </div>
          <div class="row mt-2">
            <span class="font-weight-bold col-md-2">Description:</span>
            <span class="col-md-10">{{ project.description }}</span>
          </div>
          <div class="row mt-2">
            <span class="font-weight-bold col-md-2">Address Size:</span>
            <span class="col-md-10">{{ project.address_size }}</span>
          </div>
          <div class="row mt-2">
            <span class="font-weight-bold col-md-2">Addressable Word:</span>
            <span class="col-md-10">{{ project.word_size }}</span>
          </div>
        </div>
      </div>
    </div>

    <div class="container main-div">
      <div class="table-responsive-sm">
        <table class="table table-striped">
          <thead>
          <tr class="table-primary text-center">
            <th scope="col">Version</th>
            <th scope="col">Last Modified</th>
            <th scope="col">Created</th>
            <th scope="col">Action</th>
          </tr>
          </thead>
          <tbody class="text-center">
          {% for version in versions %}
            <tr>
              <td>
                <a href="{% url 'project:register-list' version.id %}" class="text-decoration-none">
                  {{ version.name }}
                </a>
              </td>
              <td>
                {% if version.updated_at %}
                  {{ version.updated_at | date:"j/n/Y" }}
                {% else %}
                  N/A
                {% endif %}
              </td>
              <td>{{ version.updated_at | date:"j/n/Y" }}</td>
              <td>
                <a
                  class="btn btn-sm btn-success font-weight-bold modal-popup"
                  title="Copy Existing Version"
                  href="{% url 'project:version-copy' %}?version={{ version.id }}"
                >&#10697;
              </a>
                <button
                  class="btn btn-sm btn-info font-weight-bold modal-popup"
                  data-toggle="tooltip"
                  data-placement="top"
                  title="Edit Current Version"
                  data-url="{% url 'project:version-update' pk=version.id %}?project={{ project.id }}"
                  data-target="create-update-modal"
                  data-title="Update {{ version.name }}"
                >🖋
                </button>
                <button
                  class="btn btn-sm btn-danger font-weight-bold"
                  data-toggle="tooltip"
                  title="Delete Current Version"
                  id="R-delete"
                  name="V-delete-{{version.id}}"
                >&#10005;
                </button>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>

      <div class="mt-5">
        {% include 'snippets/pagination.html' %}
      </div>
    </div>
  {% endblock %}
</div>